Repository moia-oss/aws-cfg-generator, pull requests merged in 2021-03, with the labels that each got.

#3 Use `include_profile` to inherit fields from the source profile
  README.md
  aws-cfg-generator/main.go
Labels: v0.3.0

#4 Use account names as profile names
  README.md
  aws-cfg-generator/main.go
  vendor/github.com/aws/aws-sdk-go/service/organizations/api.go
  vendor/github.com/aws/aws-sdk-go/service/organizations/doc.go
  vendor/github.com/aws/aws-sdk-go/service/organizations/errors.go
  vendor/github.com/aws/aws-sdk-go/service/organizations/service.go
  vendor/modules.txt
Labels: v1.0.0

#5 Fix input_profile -> include_profile
  aws-cfg-generator/main.go
Labels: bug, v1.1.0
